// <auto-generated />
using System;
using B4Interview.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace B4Interview.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class ReviewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("B4Interview.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About");

                    b.Property<string>("EmployeeStrength");

                    b.Property<int>("Founded");

                    b.Property<string>("Headquarter");

                    b.Property<string>("Identifier");

                    b.Property<string>("Logo");

                    b.Property<string>("Name");

                    b.Property<float>("Rating");

                    b.Property<string>("Sector");

                    b.Property<string>("WebSite");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Tata Consultancy Services (TCS) helps its clients say farewell to business inefficiencies. The company is a leading global provider of IT, consulting, and outsourcing services, with operations in more than 40 countries. Its offerings include business process outsourcing, data center management, IT and strategic consulting, new product development and engineering, and systems integration. One of its specialties is developing and maintaining customized software for businesses. Most of its clients, in industries ranging from energy to financial services to retail to telecom, are located in North America, Latin America, and Europe. TCS is controlled by textiles and manufacturing conglomerate Tata Group.",
                            EmployeeStrength = "400,875",
                            Founded = 1968,
                            Headquarter = "Mumbai",
                            Identifier = "Tcs",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/b/b1/Tata_Consultancy_Services_Logo.svg",
                            Name = "Tata Consultancy Services",
                            Rating = 0f,
                            Sector = "IT services, IT consulting",
                            WebSite = "www.tcs.com"
                        });
                });

            modelBuilder.Entity("B4Interview.Models.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About");

                    b.Property<int>("CompanyId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Gallery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Tata Consultancy Services campus in Hyderabad, India",
                            CompanyId = 1,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/8/85/Tata_Consultancy_Services_Madhapur_Hyderabad.jpg"
                        },
                        new
                        {
                            Id = 2,
                            About = "TCS siruseri, Chennai",
                            CompanyId = 1,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/a/a7/TCS-Siruseri-Building.jpg"
                        });
                });

            modelBuilder.Entity("B4Interview.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AutherInfo");

                    b.Property<string>("Author");

                    b.Property<int>("CompanyId");

                    b.Property<string>("Cons");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("DownVote");

                    b.Property<string>("Pros");

                    b.Property<float>("Rating");

                    b.Property<bool>("Recommend");

                    b.Property<string>("Title");

                    b.Property<int>("UpVote");

                    b.Property<int>("ViewsCount");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutherInfo = "Current Employee - IT Analyst in Kolkata",
                            Author = "Anonymous",
                            CompanyId = 1,
                            Cons = "pay hike is less and increment is low",
                            CreatedOn = new DateTime(2019, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "I have been working at Tata Consultancy Services full-time (More than 5 years)",
                            DownVote = 0,
                            Pros = "1.best medical insurance 2. Lot of opportunities and onsite",
                            Rating = 4.5f,
                            Recommend = true,
                            Title = "good company to work",
                            UpVote = 0,
                            ViewsCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AutherInfo = "Current Employee - Assistant Systems Engineer in Chennai",
                            Author = "Anonymous",
                            CompanyId = 1,
                            Cons = "No proper transparency in management.",
                            CreatedOn = new DateTime(2018, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "I have been working at Tata Consultancy Services full-time (More than a year)",
                            DownVote = 0,
                            Pros = "Learning opportunity is more if you try yourself.",
                            Rating = 3.5f,
                            Recommend = true,
                            Title = "Good place to start with.",
                            UpVote = 0,
                            ViewsCount = 0
                        });
                });

            modelBuilder.Entity("B4Interview.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("ReviewId");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "OnSite",
                            ReviewId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Work Life Balance",
                            ReviewId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Learning",
                            ReviewId = 2
                        });
                });

            modelBuilder.Entity("B4Interview.Models.Gallery", b =>
                {
                    b.HasOne("B4Interview.Models.Company", "Company")
                        .WithMany("Images")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("B4Interview.Models.Review", b =>
                {
                    b.HasOne("B4Interview.Models.Company", "Company")
                        .WithMany("Reviews")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("B4Interview.Models.Tag", b =>
                {
                    b.HasOne("B4Interview.Models.Review", "Review")
                        .WithMany("Tags")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
